from django.urls import path
from GameApp import views


urlpatterns = [
    path("admin/",views.admin_page,name="admin"),
    path("add_category/",views.add_category,name="add_category"),
    path("save_category/",views.save_category,name="save_category"),
    path("display_category/",views.display_category,name="display_category"),
    path("edit_category/<int:cat_id>/",views.edit_category,name="edit_category"),
    path("update_category/<int:cat_id>/",views.update_category,name="update_category"),
    path("delete_category/<int:cat_id>/",views.delete_category,name="delete_category"),
    path("add_games/",views.add_games,name="add_games"),
    path("save_games/",views.save_games,name="save_games"),
    path("display_games/",views.display_games,name="display_games"),
    path("edit_games/<int:game_id>/",views.edit_games,name="edit_games"),
    path("update_games/<int:game_id>/",views.update_games,name="update_games"),
    path("delete_games/<int:game_id>/",views.delete_games,name="delete_games"),
    path("add_requirement/",views.add_requirement,name="add_requirement"),
    path("save_requirement/",views.save_requirements,name="save_requirement"),
    path("display_requirement/",views.display_requirement,name="display_requirement"),
    path("edit_requirement/<int:req_id>/",views.edit_requirement,name="edit_requirement"),
    path("update_requirement/<int:req_id>/",views.update_requirement,name="update_requirement"),
    path("delete_requirement/<int:req_id>/",views.delete_requirement,name="delete_requirement"),
    path("display_contact/",views.display_contact,name="display_contact"),
    path("delete_contact/<int:con_id>/",views.delete_contact,name="delete_contact"),
    path("login_page/",views.login_page,name="login_page"),
    path("logout/",views.logout_user,name="logout"),
    path("admin_login/",views.admin_login,name="admin_login"),
    path("account_manager",views.account_manager,name="account_manager"),
    path("delete_account/<int:us_id>/",views.delete_account,name="delete_account"),
    path("upcoming_games/",views.add_upcoming,name="upcoming_games"),
    path("save_upcoming/",views.save_upcoming,name="save_upcoming"),
    path("display_upcoming/",views.display_upcoming,name="display_upcoming"),
    path("edit_upcoming/<int:up_id>/",views.edit_upcoming,name="edit_upcoming"),
    path("update_upcoming/<int:up_id>/",views.update_upcoming,name="update_upcoming"),
    path("delete_upcoming/<int:up_id>/",views.delete_upcoming,name="delete_upcoming"),
    path("display_comments/",views.display_comments,name="display_comments"),
    path("delete_comment/<int:com_id>/",views.delete_comments,name="delete_comment"),
    path("display_feedback/",views.display_feedback,name="display_feedback"),
    path("delete_feedback/<int:feed_id>/",views.delete_feedback,name="delete_feedback"),
    path("add_fan_favorites/",views.add_fan_favorite,name="add_fan_favorites"),
    path("save_fan_favorites/",views.save_fan_favorite,name="save_fan_favorites"),
]
