# Generated by Django 5.1.2 on 2024-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Cover_Image', models.ImageField(blank=True, null=True, upload_to='Games')),
                ('Tag_Line', models.CharField(blank=True, max_length=100, null=True)),
                ('Short_Description', models.TextField(blank=True, null=True)),
                ('Summary', models.TextField(blank=True, null=True)),
                ('Genre', models.CharField(blank=True, max_length=100, null=True)),
                ('Game_Style', models.CharField(blank=True, max_length=100, null=True)),
                ('Platform', models.CharField(blank=True, max_length=100, null=True)),
                ('Release_Date', models.DateField(blank=True, null=True)),
                ('Game_Mode', models.CharField(blank=True, max_length=100, null=True)),
                ('Developer', models.CharField(blank=True, max_length=100, null=True)),
                ('Publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('Age_Rating', models.CharField(blank=True, max_length=100, null=True)),
                ('Play_Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Overall_Rating', models.IntegerField(blank=True, null=True)),
                ('Download_Link', models.URLField(blank=True, null=True)),
                ('Image1', models.ImageField(blank=True, null=True, upload_to='Games')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Games')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='Games')),
                ('Trailer', models.FileField(blank=True, null=True, upload_to='Trailers')),
            ],
        ),
    ]
