# Generated by Django 5.1.2 on 2024-11-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_game_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_db',
            name='Game_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
