# Generated by Django 5.1.2 on 2024-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0003_game_db_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_db',
            name='Release_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
