# Generated by Django 5.1.2 on 2024-11-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0004_alter_game_db_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requirement_Game', models.CharField(blank=True, max_length=100, null=True)),
                ('Minimum_OperatingSystem', models.CharField(blank=True, max_length=100, null=True)),
                ('Maximum_OperatingSystem', models.CharField(blank=True, max_length=100, null=True)),
                ('Minimum_RAM', models.CharField(blank=True, max_length=100, null=True)),
                ('Maximum_RAM', models.CharField(blank=True, max_length=100, null=True)),
                ('Minimum_Processor', models.CharField(blank=True, max_length=100, null=True)),
                ('Maximum_Processor', models.CharField(blank=True, max_length=100, null=True)),
                ('Minimum_Graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('Maximum_Graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('Minimum_Storage', models.CharField(blank=True, max_length=100, null=True)),
                ('Maximum_Storage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
