# Generated by Django 5.1.2 on 2024-11-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0005_requirement_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Up_Cover_Image', models.ImageField(blank=True, null=True, upload_to='Games')),
                ('Up_Game_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Tag_Line', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Short_Description', models.TextField(blank=True, null=True)),
                ('Up_Summary', models.TextField(blank=True, null=True)),
                ('Up_Genre', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Game_Style', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Platform', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Release_Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Game_Mode', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Developer', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Age_Rating', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Play_Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Up_Overall_Rating', models.IntegerField(blank=True, null=True)),
                ('Up_Trailer', models.FileField(blank=True, null=True, upload_to='Trailers')),
            ],
        ),
    ]
