# Generated by Django 5.1.2 on 2024-11-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0006_upcoming_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming_db',
            name='Up_Inside_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Games'),
        ),
    ]
