# Generated by Django 5.1.2 on 2024-12-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0007_upcoming_db_up_inside_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan_Favorite_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fan_Game', models.CharField(blank=True, max_length=100, null=True)),
                ('Fan_Created', models.DateTimeField(auto_now_add=True)),
                ('Fan_Description', models.TextField(blank=True, null=True)),
                ('Fan_Image', models.ImageField(blank=True, null=True, upload_to='fan_favorite')),
                ('Reason1', models.CharField(blank=True, max_length=100, null=True)),
                ('Reason2', models.CharField(blank=True, max_length=100, null=True)),
                ('Reason3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
