# Generated by Django 5.1.2 on 2024-11-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_login_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('User_Image', models.CharField(blank=True, max_length=255, null=True)),
                ('User_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_Time', models.DateTimeField(auto_now_add=True)),
                ('Comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
