# Generated by Django 5.1.2 on 2024-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_comment_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fav_Cover', models.CharField(blank=True, max_length=255, null=True)),
                ('Fav_Gname', models.CharField(blank=True, max_length=100, null=True)),
                ('Fav_Age', models.CharField(blank=True, max_length=100, null=True)),
                ('Fav_Overall', models.IntegerField(blank=True, null=True)),
                ('Fav_User', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
