# Generated by Django 5.1.2 on 2024-11-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_favorite_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_db',
            name='Fav_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
