# Generated by Django 5.1.2 on 2024-12-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_favorite_db_fav_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Blog_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Blog_Fav', models.CharField(blank=True, max_length=100, null=True)),
                ('Blog_Feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
