# Generated by Django 5.1.2 on 2026-07-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_blog_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_db',
            name='Profile_Image_URL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
