# Generated by Django 5.1.2 on 2026-07-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_login_db_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_db',
            name='Mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='login_db',
            name='Mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
